export interface IStarship {
    name: string,
    model: string,
    starship_class: string,
    manufacturer: string,
    cost_in_credits: string,
    length: string,
    crew: string,
    passengers: string,
    cargo_capacity: string,
    created: string,
    edited: string,
    max_atmosphering_speed?: string,
    hyperdrive_rating?: string,
    consumables?: string,
    MGLT?: string,
    url?: string,
    films?: string[],
    pilots?: string[],
    img?: string
}